### ISSUE TITLE
about the Pseudo-abnormal data set

### ISSUE THREAD

**Issue by Smallwhite999** [lilygeorgescu/AED#1]
This is a great job. Please provide it with the Pseudo-abnormal data set used in this work，This will be very helpful for further understanding and research on this work，thanks a lot！

**Comment by lilygeorgescu** [comment]
Hi,

Thank you for your interest in our work.
Unfortunately, due to license of the images, we cannot host them online. Please download the specified data sets from their websites and select the samples specified in our work.

Best,
Lili
