### ISSUE TITLE
Code request after signing and sending emails to specified application address

### ISSUE THREAD

**Issue by JPerAsperaadAstra** [lilygeorgescu/AED#2]
Hello, dear authors. Thanks for your great work and I'm willing to try this method out. I sent emails to this repository's specified application address but got no reply up to now.
Could you please check and reply to my request email? Thanks a lot :)

**Comment by lilygeorgescu** [comment]
hi, i could not find any email from you. please resend your email. 

Best

**Comment by JPerAsperaadAstra** [comment]
Sorry about the misunderstanding, email application has been resent, thanks
